### PR TITLE
More diligent dependencies

### PR DESCRIPTION
**Pull request by Leonidas-from-XIV**
When used [in RWO](https://ci.ocamllabs.io/github/realworldocaml/book/commit/7b1760f0cb007451d3c17f6a1452887089de201b/variant/debian-11-4.14) there is a build failure related to `num`:

```
File "duniverse/num/src/dune", line 14, characters 21-24:
14 |   (c_names nat_stubs bng bng_generic)
                          ^^^
bng.c:23:10: fatal error: bng_amd64.c: No such file or directory
   23 | #include "bng_amd64.c"
      |          ^~~~~~~~~~~~~
compilation terminated.
```

Unfortunately, I can't reproduce it locally so what I did was to refactor the dune build files that `num` ships with:

  * Use dune 2.x
  * Use the `foreign_stubs` stanza
  * Declare the `.c` files as dependencies explicitly

I then tried to [see whether it works on OCaml CI](https://github.com/realworldocaml/book/pull/3628) stop failing on `num`, therefore I'm submitting the changes as PR.

### CODE REVIEW

**Review by NathanReb — APPROVED** [review]
The changes look sensible to me either way! Thanks for taking care of this!

**Comment by NathanReb** [comment]
Out of curiosity, do you know if there's a chance we could upstream those changes?

**Comment by Leonidas-from-XIV** [comment]
> Out of curiosity, do you know if there's a chance we could upstream those changes?

I was considering the same, I guess it is worth trying!

**Comment by Leonidas-from-XIV** [comment]
Looking at [upstream](https://github.com/ocaml/num/blob/703e1f883c8728ed0abaed6e2d5cdd3fc7e3cb46/src/dune), turns out a lot of these fixes have already been applied. In a slightly different way than in our port but the next release should probably just work again with only the opam file redirection.

**Pull request merged**
